# Site settings
title: AC Taiwan
email: ashton@ashtonc.ca
description: > # this means to ignore newlines until "baseurl:"
  Source hosted on [GitHub](https://github.com/ashtonc/taiwanblog).
baseurl: "/taiwan" # the subpath of your site, e.g. /blog/
url: "http://ashtonc.ca" # the base hostname & protocol for your site
twitter_username: ashtonabc
github_username:  ashtonc
paginate: 4

# Files
exclude: [README.md]

# Build settings
markdown: kramdown
highlighter: rouge
